all:
		#./program obj_str_double.json
		./program obj_str_arr.json
		#./program obj_str_integer.json
		#./program obj_str_nll.json
		# ./program obj_str_obj.json
		#./program obj_str_str.json
		#./program obj_str_true.json
		#./program obj_str_false.json
