all:
		valgrind ./program obj_str_double.json
		valgrind  ./program obj_array1.json
		valgrind ./program obj_str_arr.json
		valgrind ./program obj_str_integer.json
		valgrind ./program obj_str_nll.json
		valgrind  ./program obj_str_obj.json
		valgrind ./program obj_str_str.json
		valgrind ./program obj_str_true.json
		valgrind ./program obj_str_false.json
